apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment-ingestion.yaml
  - ../../base/deployment-analytics.yaml

namePrefix: aws-

commonLabels:
  cloud.provider: aws
  cluster.type: eks-fargate
